# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0014_auto_20160713_1331'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('relevance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Relevancia')),
                ('interest', models.PositiveIntegerField(blank=True, null=True, verbose_name='Interés General')),
                ('newness', models.PositiveIntegerField(blank=True, null=True, verbose_name='Novedad')),
                ('conflict', models.BooleanField(default=False, verbose_name='¿Existe un conflico de intereses?')),
                ('finished', models.BooleanField(default=False, verbose_name='¿Revisión finalizada?')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='proposals.Proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('user', 'proposal')]),
        ),
    ]
