# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del revisor'),
        ),
    ]
