# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0003_auto_20160725_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restore_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
