# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_auto_20160627_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalbase',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposalbase',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
