# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 22:28
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('proposals', '0014_auto_20160713_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
