# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 07:56
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_proposal_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Lista de etiquetas separadas por comas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
    ]
