# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 08:13
from __future__ import unicode_literals

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_auto_20160818_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Lista de etiquetas separadas por comas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
    ]
