# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_auto_20160818_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalbase',
            name='accepted',
            field=models.NullBooleanField(default=None, verbose_name='Aceptada'),
        ),
        migrations.AddField(
            model_name='proposalbase',
            name='accepted_notified',
            field=models.BooleanField(default=False, verbose_name='Notificación de aceptación enviada'),
        ),
    ]
