# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0005_auto_20150918_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='_biography_ca_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='_biography_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='_biography_es_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='_biography_eu_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='_biography_gl_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="A little bit about you.  Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", rendered_field=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_ca',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="A little bit about you.  Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_ca_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_en',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="A little bit about you.  Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_es',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="A little bit about you.  Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_eu',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="A little bit about you.  Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_eu_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_gl',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="A little bit about you.  Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_gl_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
    ]
