# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_auto_20160723_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='invite_email',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='invite_token',
        ),
        migrations.AddField(
            model_name='speaker',
            name='is_keynoter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
