# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0007_auto_20160916_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='restore_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
