# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20150625_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='_abstract_ca_rendered',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='_abstract_eu_rendered',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='_abstract_ga_rendered',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='_description_ca_rendered',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='_description_eu_rendered',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='_description_ga_rendered',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='abstract_ca',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='abstract_ca_markup_type',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='abstract_eu',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='abstract_eu_markup_type',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='abstract_ga',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='abstract_ga_markup_type',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='description_ca_markup_type',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='description_eu',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='description_eu_markup_type',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='description_ga',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='description_ga_markup_type',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='title_eu',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='title_ga',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_eu',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_ga',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='_content_override_ca_rendered',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='_content_override_eu_rendered',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='_content_override_ga_rendered',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='content_override_ca',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='content_override_ca_markup_type',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='content_override_eu',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='content_override_eu_markup_type',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='content_override_ga',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='content_override_ga_markup_type',
        ),
        migrations.RemoveField(
            model_name='slotkind',
            name='label_ca',
        ),
        migrations.RemoveField(
            model_name='slotkind',
            name='label_eu',
        ),
        migrations.RemoveField(
            model_name='slotkind',
            name='label_ga',
        ),
    ]
