# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20160201_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='_abstract_ca_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_abstract_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_abstract_es_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_abstract_eu_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_abstract_gl_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_description_ca_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_description_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_description_es_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_description_eu_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='_description_gl_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_ca_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_eu_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_gl_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_ca_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_eu_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_gl_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='_content_override_ca_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='_content_override_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='_content_override_es_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='_content_override_eu_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='_content_override_gl_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='content_override_ca_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='content_override_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='content_override_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='content_override_eu_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='content_override_gl_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='content_override_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30),
        ),
    ]
