# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotkind',
            name='class_attr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
