# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_slotkind_class_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
