# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_slot_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='is_workshop',
        ),
        migrations.AddField(
            model_name='track',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Day'),
        ),
    ]
