# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20160905_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
